// ─────────────────────────────────────────────────────────────────────────────
// Complete country data for the interactive globe (195 UN member states + territories)
// Includes visa status for Indian passport holders, safety levels, and key info
// ─────────────────────────────────────────────────────────────────────────────

export interface CountryData {
  name: string;
  iso3: string;
  iso2: string;
  capital: string;
  region: string;
  continent: string;
  population: string;
  currency: string;
  currencyCode: string;
  languages: string[];
  lat: number;
  lng: number;
  visaStatus: "visa-free" | "visa-on-arrival" | "e-visa" | "visa-required";
  visaNote: string;
  safetyLevel: "safe" | "moderate" | "caution" | "avoid";
  flagEmoji: string;
  callingCode: string;
  timezone: string;
}

export const COUNTRY_DATA: CountryData[] = [
  // ═══════ ASIA ═══════
  { name: "Afghanistan", iso3: "AFG", iso2: "AF", capital: "Kabul", region: "Central Asia", continent: "Asia", population: "41M", currency: "Afghani", currencyCode: "AFN", languages: ["Pashto", "Dari"], lat: 33.93, lng: 67.71, visaStatus: "visa-required", visaNote: "Visa required. Travel advisory in effect.", safetyLevel: "avoid", flagEmoji: "🇦🇫", callingCode: "+93", timezone: "UTC+4:30" },
  { name: "Armenia", iso3: "ARM", iso2: "AM", capital: "Yerevan", region: "Western Asia", continent: "Asia", population: "3M", currency: "Dram", currencyCode: "AMD", languages: ["Armenian"], lat: 40.07, lng: 45.04, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 120 days.", safetyLevel: "safe", flagEmoji: "🇦🇲", callingCode: "+374", timezone: "UTC+4" },
  { name: "Azerbaijan", iso3: "AZE", iso2: "AZ", capital: "Baku", region: "Western Asia", continent: "Asia", population: "10M", currency: "Manat", currencyCode: "AZN", languages: ["Azerbaijani"], lat: 40.14, lng: 47.58, visaStatus: "e-visa", visaNote: "E-visa available for 30 days.", safetyLevel: "safe", flagEmoji: "🇦🇿", callingCode: "+994", timezone: "UTC+4" },
  { name: "Bahrain", iso3: "BHR", iso2: "BH", capital: "Manama", region: "Middle East", continent: "Asia", population: "1.5M", currency: "Dinar", currencyCode: "BHD", languages: ["Arabic"], lat: 26.07, lng: 50.55, visaStatus: "e-visa", visaNote: "E-visa available for 14 days.", safetyLevel: "safe", flagEmoji: "🇧🇭", callingCode: "+973", timezone: "UTC+3" },
  { name: "Bangladesh", iso3: "BGD", iso2: "BD", capital: "Dhaka", region: "South Asia", continent: "Asia", population: "170M", currency: "Taka", currencyCode: "BDT", languages: ["Bengali"], lat: 23.68, lng: 90.36, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "moderate", flagEmoji: "🇧🇩", callingCode: "+880", timezone: "UTC+6" },
  { name: "Bhutan", iso3: "BTN", iso2: "BT", capital: "Thimphu", region: "South Asia", continent: "Asia", population: "0.8M", currency: "Ngultrum", currencyCode: "BTN", languages: ["Dzongkha"], lat: 27.51, lng: 90.43, visaStatus: "visa-required", visaNote: "Pre-arranged visa required through tour operator.", safetyLevel: "safe", flagEmoji: "🇧🇹", callingCode: "+975", timezone: "UTC+6" },
  { name: "Brunei", iso3: "BRN", iso2: "BN", capital: "Bandar Seri Begawan", region: "Southeast Asia", continent: "Asia", population: "0.4M", currency: "Dollar", currencyCode: "BND", languages: ["Malay"], lat: 4.94, lng: 114.95, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 14 days.", safetyLevel: "safe", flagEmoji: "🇧🇳", callingCode: "+673", timezone: "UTC+8" },
  { name: "Cambodia", iso3: "KHM", iso2: "KH", capital: "Phnom Penh", region: "Southeast Asia", continent: "Asia", population: "17M", currency: "Riel", currencyCode: "KHR", languages: ["Khmer"], lat: 12.57, lng: 104.99, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival or e-visa for 30 days.", safetyLevel: "moderate", flagEmoji: "🇰🇭", callingCode: "+855", timezone: "UTC+7" },
  { name: "China", iso3: "CHN", iso2: "CN", capital: "Beijing", region: "East Asia", continent: "Asia", population: "1.43B", currency: "Yuan", currencyCode: "CNY", languages: ["Mandarin"], lat: 35.86, lng: 104.19, visaStatus: "visa-required", visaNote: "Visa required. Apply at Chinese embassy.", safetyLevel: "safe", flagEmoji: "🇨🇳", callingCode: "+86", timezone: "UTC+8" },
  { name: "Georgia", iso3: "GEO", iso2: "GE", capital: "Tbilisi", region: "Western Asia", continent: "Asia", population: "3.7M", currency: "Lari", currencyCode: "GEL", languages: ["Georgian"], lat: 42.32, lng: 43.36, visaStatus: "e-visa", visaNote: "E-visa available for 90 days.", safetyLevel: "safe", flagEmoji: "🇬🇪", callingCode: "+995", timezone: "UTC+4" },
  { name: "India", iso3: "IND", iso2: "IN", capital: "New Delhi", region: "South Asia", continent: "Asia", population: "1.44B", currency: "Rupee", currencyCode: "INR", languages: ["Hindi", "English"], lat: 20.59, lng: 78.96, visaStatus: "visa-free", visaNote: "Home country.", safetyLevel: "safe", flagEmoji: "🇮🇳", callingCode: "+91", timezone: "UTC+5:30" },
  { name: "Indonesia", iso3: "IDN", iso2: "ID", capital: "Jakarta", region: "Southeast Asia", continent: "Asia", population: "277M", currency: "Rupiah", currencyCode: "IDR", languages: ["Indonesian"], lat: -0.79, lng: 113.92, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "moderate", flagEmoji: "🇮🇩", callingCode: "+62", timezone: "UTC+7" },
  { name: "Iran", iso3: "IRN", iso2: "IR", capital: "Tehran", region: "Middle East", continent: "Asia", population: "87M", currency: "Rial", currencyCode: "IRR", languages: ["Persian"], lat: 32.43, lng: 53.69, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days at airports.", safetyLevel: "caution", flagEmoji: "🇮🇷", callingCode: "+98", timezone: "UTC+3:30" },
  { name: "Iraq", iso3: "IRQ", iso2: "IQ", capital: "Baghdad", region: "Middle East", continent: "Asia", population: "44M", currency: "Dinar", currencyCode: "IQD", languages: ["Arabic", "Kurdish"], lat: 33.22, lng: 43.68, visaStatus: "visa-required", visaNote: "Visa required. Security advisory.", safetyLevel: "avoid", flagEmoji: "🇮🇶", callingCode: "+964", timezone: "UTC+3" },
  { name: "Israel", iso3: "ISR", iso2: "IL", capital: "Jerusalem", region: "Middle East", continent: "Asia", population: "9.3M", currency: "Shekel", currencyCode: "ILS", languages: ["Hebrew", "Arabic"], lat: 31.05, lng: 34.85, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇮🇱", callingCode: "+972", timezone: "UTC+2" },
  { name: "Japan", iso3: "JPN", iso2: "JP", capital: "Tokyo", region: "East Asia", continent: "Asia", population: "125M", currency: "Yen", currencyCode: "JPY", languages: ["Japanese"], lat: 36.20, lng: 138.25, visaStatus: "visa-required", visaNote: "Visa required. Apply at Japanese embassy.", safetyLevel: "safe", flagEmoji: "🇯🇵", callingCode: "+81", timezone: "UTC+9" },
  { name: "Jordan", iso3: "JOR", iso2: "JO", capital: "Amman", region: "Middle East", continent: "Asia", population: "11M", currency: "Dinar", currencyCode: "JOD", languages: ["Arabic"], lat: 30.58, lng: 36.24, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "moderate", flagEmoji: "🇯🇴", callingCode: "+962", timezone: "UTC+2" },
  { name: "Kazakhstan", iso3: "KAZ", iso2: "KZ", capital: "Astana", region: "Central Asia", continent: "Asia", population: "19M", currency: "Tenge", currencyCode: "KZT", languages: ["Kazakh", "Russian"], lat: 48.02, lng: 66.92, visaStatus: "visa-free", visaNote: "Visa-free for 14 days.", safetyLevel: "safe", flagEmoji: "🇰🇿", callingCode: "+7", timezone: "UTC+6" },
  { name: "Kuwait", iso3: "KWT", iso2: "KW", capital: "Kuwait City", region: "Middle East", continent: "Asia", population: "4.3M", currency: "Dinar", currencyCode: "KWD", languages: ["Arabic"], lat: 29.31, lng: 47.48, visaStatus: "visa-required", visaNote: "Visa required. Apply before travel.", safetyLevel: "safe", flagEmoji: "🇰🇼", callingCode: "+965", timezone: "UTC+3" },
  { name: "Kyrgyzstan", iso3: "KGZ", iso2: "KG", capital: "Bishkek", region: "Central Asia", continent: "Asia", population: "6.7M", currency: "Som", currencyCode: "KGS", languages: ["Kyrgyz", "Russian"], lat: 41.20, lng: 74.77, visaStatus: "e-visa", visaNote: "E-visa available for 30 days.", safetyLevel: "safe", flagEmoji: "🇰🇬", callingCode: "+996", timezone: "UTC+6" },
  { name: "Laos", iso3: "LAO", iso2: "LA", capital: "Vientiane", region: "Southeast Asia", continent: "Asia", population: "7.4M", currency: "Kip", currencyCode: "LAK", languages: ["Lao"], lat: 19.86, lng: 102.50, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "safe", flagEmoji: "🇱🇦", callingCode: "+856", timezone: "UTC+7" },
  { name: "Lebanon", iso3: "LBN", iso2: "LB", capital: "Beirut", region: "Middle East", continent: "Asia", population: "5.5M", currency: "Pound", currencyCode: "LBP", languages: ["Arabic"], lat: 33.85, lng: 35.86, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇱🇧", callingCode: "+961", timezone: "UTC+2" },
  { name: "Malaysia", iso3: "MYS", iso2: "MY", capital: "Kuala Lumpur", region: "Southeast Asia", continent: "Asia", population: "33M", currency: "Ringgit", currencyCode: "MYR", languages: ["Malay"], lat: 4.21, lng: 101.97, visaStatus: "visa-free", visaNote: "Visa-free for 30 days.", safetyLevel: "safe", flagEmoji: "🇲🇾", callingCode: "+60", timezone: "UTC+8" },
  { name: "Maldives", iso3: "MDV", iso2: "MV", capital: "Malé", region: "South Asia", continent: "Asia", population: "0.5M", currency: "Rufiyaa", currencyCode: "MVR", languages: ["Dhivehi"], lat: 3.20, lng: 73.22, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "safe", flagEmoji: "🇲🇻", callingCode: "+960", timezone: "UTC+5" },
  { name: "Mongolia", iso3: "MNG", iso2: "MN", capital: "Ulaanbaatar", region: "East Asia", continent: "Asia", population: "3.3M", currency: "Tugrik", currencyCode: "MNT", languages: ["Mongolian"], lat: 46.86, lng: 103.85, visaStatus: "visa-required", visaNote: "Visa required for Indian passport.", safetyLevel: "safe", flagEmoji: "🇲🇳", callingCode: "+976", timezone: "UTC+8" },
  { name: "Myanmar", iso3: "MMR", iso2: "MM", capital: "Naypyidaw", region: "Southeast Asia", continent: "Asia", population: "55M", currency: "Kyat", currencyCode: "MMK", languages: ["Burmese"], lat: 21.91, lng: 95.96, visaStatus: "e-visa", visaNote: "E-visa available for 28 days.", safetyLevel: "caution", flagEmoji: "🇲🇲", callingCode: "+95", timezone: "UTC+6:30" },
  { name: "Nepal", iso3: "NPL", iso2: "NP", capital: "Kathmandu", region: "South Asia", continent: "Asia", population: "30M", currency: "Rupee", currencyCode: "NPR", languages: ["Nepali"], lat: 28.39, lng: 84.12, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 15/30/90 days.", safetyLevel: "safe", flagEmoji: "🇳🇵", callingCode: "+977", timezone: "UTC+5:45" },
  { name: "North Korea", iso3: "PRK", iso2: "KP", capital: "Pyongyang", region: "East Asia", continent: "Asia", population: "26M", currency: "Won", currencyCode: "KPW", languages: ["Korean"], lat: 40.34, lng: 127.51, visaStatus: "visa-required", visaNote: "Restricted. Organized tours only.", safetyLevel: "avoid", flagEmoji: "🇰🇵", callingCode: "+850", timezone: "UTC+9" },
  { name: "Oman", iso3: "OMN", iso2: "OM", capital: "Muscat", region: "Middle East", continent: "Asia", population: "5.1M", currency: "Rial", currencyCode: "OMR", languages: ["Arabic"], lat: 21.47, lng: 55.98, visaStatus: "e-visa", visaNote: "E-visa available for 10/30 days.", safetyLevel: "safe", flagEmoji: "🇴🇲", callingCode: "+968", timezone: "UTC+4" },
  { name: "Pakistan", iso3: "PAK", iso2: "PK", capital: "Islamabad", region: "South Asia", continent: "Asia", population: "230M", currency: "Rupee", currencyCode: "PKR", languages: ["Urdu", "English"], lat: 30.38, lng: 69.35, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇵🇰", callingCode: "+92", timezone: "UTC+5" },
  { name: "Palestine", iso3: "PSE", iso2: "PS", capital: "Ramallah", region: "Middle East", continent: "Asia", population: "5.4M", currency: "Shekel", currencyCode: "ILS", languages: ["Arabic"], lat: 31.95, lng: 35.23, visaStatus: "visa-required", visaNote: "Complex entry. Israeli visa needed.", safetyLevel: "avoid", flagEmoji: "🇵🇸", callingCode: "+970", timezone: "UTC+2" },
  { name: "Philippines", iso3: "PHL", iso2: "PH", capital: "Manila", region: "Southeast Asia", continent: "Asia", population: "115M", currency: "Peso", currencyCode: "PHP", languages: ["Filipino", "English"], lat: 12.88, lng: 121.77, visaStatus: "visa-free", visaNote: "Visa-free for 30 days.", safetyLevel: "moderate", flagEmoji: "🇵🇭", callingCode: "+63", timezone: "UTC+8" },
  { name: "Qatar", iso3: "QAT", iso2: "QA", capital: "Doha", region: "Middle East", continent: "Asia", population: "2.9M", currency: "Riyal", currencyCode: "QAR", languages: ["Arabic"], lat: 25.35, lng: 51.18, visaStatus: "visa-on-arrival", visaNote: "Visa waiver for 30 days.", safetyLevel: "safe", flagEmoji: "🇶🇦", callingCode: "+974", timezone: "UTC+3" },
  { name: "Saudi Arabia", iso3: "SAU", iso2: "SA", capital: "Riyadh", region: "Middle East", continent: "Asia", population: "36M", currency: "Riyal", currencyCode: "SAR", languages: ["Arabic"], lat: 23.88, lng: 45.08, visaStatus: "e-visa", visaNote: "E-visa available for tourism.", safetyLevel: "safe", flagEmoji: "🇸🇦", callingCode: "+966", timezone: "UTC+3" },
  { name: "Singapore", iso3: "SGP", iso2: "SG", capital: "Singapore", region: "Southeast Asia", continent: "Asia", population: "5.9M", currency: "Dollar", currencyCode: "SGD", languages: ["English", "Malay", "Mandarin", "Tamil"], lat: 1.35, lng: 103.82, visaStatus: "visa-required", visaNote: "Visa required. Apply online or at embassy.", safetyLevel: "safe", flagEmoji: "🇸🇬", callingCode: "+65", timezone: "UTC+8" },
  { name: "South Korea", iso3: "KOR", iso2: "KR", capital: "Seoul", region: "East Asia", continent: "Asia", population: "51M", currency: "Won", currencyCode: "KRW", languages: ["Korean"], lat: 35.91, lng: 127.77, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇰🇷", callingCode: "+82", timezone: "UTC+9" },
  { name: "Sri Lanka", iso3: "LKA", iso2: "LK", capital: "Colombo", region: "South Asia", continent: "Asia", population: "22M", currency: "Rupee", currencyCode: "LKR", languages: ["Sinhala", "Tamil"], lat: 7.87, lng: 80.77, visaStatus: "e-visa", visaNote: "E-visa (ETA) for 30 days.", safetyLevel: "safe", flagEmoji: "🇱🇰", callingCode: "+94", timezone: "UTC+5:30" },
  { name: "Syria", iso3: "SYR", iso2: "SY", capital: "Damascus", region: "Middle East", continent: "Asia", population: "22M", currency: "Pound", currencyCode: "SYP", languages: ["Arabic"], lat: 34.80, lng: 38.99, visaStatus: "visa-required", visaNote: "Travel not advised.", safetyLevel: "avoid", flagEmoji: "🇸🇾", callingCode: "+963", timezone: "UTC+2" },
  { name: "Tajikistan", iso3: "TJK", iso2: "TJ", capital: "Dushanbe", region: "Central Asia", continent: "Asia", population: "10M", currency: "Somoni", currencyCode: "TJS", languages: ["Tajik"], lat: 38.86, lng: 71.28, visaStatus: "e-visa", visaNote: "E-visa available for 45 days.", safetyLevel: "moderate", flagEmoji: "🇹🇯", callingCode: "+992", timezone: "UTC+5" },
  { name: "Thailand", iso3: "THA", iso2: "TH", capital: "Bangkok", region: "Southeast Asia", continent: "Asia", population: "72M", currency: "Baht", currencyCode: "THB", languages: ["Thai"], lat: 15.87, lng: 100.99, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 15 days.", safetyLevel: "safe", flagEmoji: "🇹🇭", callingCode: "+66", timezone: "UTC+7" },
  { name: "Timor-Leste", iso3: "TLS", iso2: "TL", capital: "Dili", region: "Southeast Asia", continent: "Asia", population: "1.3M", currency: "US Dollar", currencyCode: "USD", languages: ["Tetum", "Portuguese"], lat: -8.87, lng: 125.73, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "moderate", flagEmoji: "🇹🇱", callingCode: "+670", timezone: "UTC+9" },
  { name: "Turkey", iso3: "TUR", iso2: "TR", capital: "Ankara", region: "Western Asia", continent: "Asia", population: "85M", currency: "Lira", currencyCode: "TRY", languages: ["Turkish"], lat: 38.96, lng: 35.24, visaStatus: "e-visa", visaNote: "E-visa available for 30 days.", safetyLevel: "moderate", flagEmoji: "🇹🇷", callingCode: "+90", timezone: "UTC+3" },
  { name: "Turkmenistan", iso3: "TKM", iso2: "TM", capital: "Ashgabat", region: "Central Asia", continent: "Asia", population: "6.3M", currency: "Manat", currencyCode: "TMT", languages: ["Turkmen"], lat: 38.97, lng: 59.56, visaStatus: "visa-required", visaNote: "Letter of invitation required.", safetyLevel: "moderate", flagEmoji: "🇹🇲", callingCode: "+993", timezone: "UTC+5" },
  { name: "United Arab Emirates", iso3: "ARE", iso2: "AE", capital: "Abu Dhabi", region: "Middle East", continent: "Asia", population: "10M", currency: "Dirham", currencyCode: "AED", languages: ["Arabic"], lat: 23.42, lng: 53.85, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 14 days.", safetyLevel: "safe", flagEmoji: "🇦🇪", callingCode: "+971", timezone: "UTC+4" },
  { name: "Uzbekistan", iso3: "UZB", iso2: "UZ", capital: "Tashkent", region: "Central Asia", continent: "Asia", population: "35M", currency: "Som", currencyCode: "UZS", languages: ["Uzbek"], lat: 41.38, lng: 64.59, visaStatus: "e-visa", visaNote: "E-visa available for 30 days.", safetyLevel: "safe", flagEmoji: "🇺🇿", callingCode: "+998", timezone: "UTC+5" },
  { name: "Vietnam", iso3: "VNM", iso2: "VN", capital: "Hanoi", region: "Southeast Asia", continent: "Asia", population: "99M", currency: "Dong", currencyCode: "VND", languages: ["Vietnamese"], lat: 14.06, lng: 108.28, visaStatus: "e-visa", visaNote: "E-visa for 30 days.", safetyLevel: "safe", flagEmoji: "🇻🇳", callingCode: "+84", timezone: "UTC+7" },
  { name: "Yemen", iso3: "YEM", iso2: "YE", capital: "Sana'a", region: "Middle East", continent: "Asia", population: "33M", currency: "Rial", currencyCode: "YER", languages: ["Arabic"], lat: 15.55, lng: 48.52, visaStatus: "visa-required", visaNote: "Travel not advised. Active conflict.", safetyLevel: "avoid", flagEmoji: "🇾🇪", callingCode: "+967", timezone: "UTC+3" },

  // ═══════ EUROPE ═══════
  { name: "Albania", iso3: "ALB", iso2: "AL", capital: "Tirana", region: "Southern Europe", continent: "Europe", population: "2.8M", currency: "Lek", currencyCode: "ALL", languages: ["Albanian"], lat: 41.15, lng: 20.17, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇦🇱", callingCode: "+355", timezone: "UTC+1" },
  { name: "Andorra", iso3: "AND", iso2: "AD", capital: "Andorra la Vella", region: "Southern Europe", continent: "Europe", population: "0.08M", currency: "Euro", currencyCode: "EUR", languages: ["Catalan"], lat: 42.55, lng: 1.60, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇦🇩", callingCode: "+376", timezone: "UTC+1" },
  { name: "Austria", iso3: "AUT", iso2: "AT", capital: "Vienna", region: "Western Europe", continent: "Europe", population: "9M", currency: "Euro", currencyCode: "EUR", languages: ["German"], lat: 47.52, lng: 14.55, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇦🇹", callingCode: "+43", timezone: "UTC+1" },
  { name: "Belarus", iso3: "BLR", iso2: "BY", capital: "Minsk", region: "Eastern Europe", continent: "Europe", population: "9.4M", currency: "Ruble", currencyCode: "BYN", languages: ["Belarusian", "Russian"], lat: 53.71, lng: 27.95, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇧🇾", callingCode: "+375", timezone: "UTC+3" },
  { name: "Belgium", iso3: "BEL", iso2: "BE", capital: "Brussels", region: "Western Europe", continent: "Europe", population: "11.5M", currency: "Euro", currencyCode: "EUR", languages: ["Dutch", "French", "German"], lat: 50.50, lng: 4.47, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇧🇪", callingCode: "+32", timezone: "UTC+1" },
  { name: "Bosnia and Herzegovina", iso3: "BIH", iso2: "BA", capital: "Sarajevo", region: "Southern Europe", continent: "Europe", population: "3.3M", currency: "Marka", currencyCode: "BAM", languages: ["Bosnian", "Croatian", "Serbian"], lat: 43.92, lng: 17.68, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇧🇦", callingCode: "+387", timezone: "UTC+1" },
  { name: "Bulgaria", iso3: "BGR", iso2: "BG", capital: "Sofia", region: "Eastern Europe", continent: "Europe", population: "6.9M", currency: "Lev", currencyCode: "BGN", languages: ["Bulgarian"], lat: 42.73, lng: 25.49, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇧🇬", callingCode: "+359", timezone: "UTC+2" },
  { name: "Croatia", iso3: "HRV", iso2: "HR", capital: "Zagreb", region: "Southern Europe", continent: "Europe", population: "3.9M", currency: "Euro", currencyCode: "EUR", languages: ["Croatian"], lat: 45.10, lng: 15.20, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇭🇷", callingCode: "+385", timezone: "UTC+1" },
  { name: "Cyprus", iso3: "CYP", iso2: "CY", capital: "Nicosia", region: "Southern Europe", continent: "Europe", population: "1.2M", currency: "Euro", currencyCode: "EUR", languages: ["Greek", "Turkish"], lat: 35.13, lng: 33.43, visaStatus: "visa-required", visaNote: "Cyprus visa or Schengen with conditions.", safetyLevel: "safe", flagEmoji: "🇨🇾", callingCode: "+357", timezone: "UTC+2" },
  { name: "Czech Republic", iso3: "CZE", iso2: "CZ", capital: "Prague", region: "Central Europe", continent: "Europe", population: "10.8M", currency: "Koruna", currencyCode: "CZK", languages: ["Czech"], lat: 49.82, lng: 15.47, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇨🇿", callingCode: "+420", timezone: "UTC+1" },
  { name: "Denmark", iso3: "DNK", iso2: "DK", capital: "Copenhagen", region: "Northern Europe", continent: "Europe", population: "5.9M", currency: "Krone", currencyCode: "DKK", languages: ["Danish"], lat: 56.26, lng: 9.50, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇩🇰", callingCode: "+45", timezone: "UTC+1" },
  { name: "Estonia", iso3: "EST", iso2: "EE", capital: "Tallinn", region: "Northern Europe", continent: "Europe", population: "1.3M", currency: "Euro", currencyCode: "EUR", languages: ["Estonian"], lat: 58.60, lng: 25.01, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇪🇪", callingCode: "+372", timezone: "UTC+2" },
  { name: "Finland", iso3: "FIN", iso2: "FI", capital: "Helsinki", region: "Northern Europe", continent: "Europe", population: "5.5M", currency: "Euro", currencyCode: "EUR", languages: ["Finnish", "Swedish"], lat: 61.92, lng: 25.75, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇫🇮", callingCode: "+358", timezone: "UTC+2" },
  { name: "France", iso3: "FRA", iso2: "FR", capital: "Paris", region: "Western Europe", continent: "Europe", population: "68M", currency: "Euro", currencyCode: "EUR", languages: ["French"], lat: 46.23, lng: 2.21, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇫🇷", callingCode: "+33", timezone: "UTC+1" },
  { name: "Germany", iso3: "DEU", iso2: "DE", capital: "Berlin", region: "Western Europe", continent: "Europe", population: "84M", currency: "Euro", currencyCode: "EUR", languages: ["German"], lat: 51.17, lng: 10.45, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇩🇪", callingCode: "+49", timezone: "UTC+1" },
  { name: "Greece", iso3: "GRC", iso2: "GR", capital: "Athens", region: "Southern Europe", continent: "Europe", population: "10.7M", currency: "Euro", currencyCode: "EUR", languages: ["Greek"], lat: 39.07, lng: 21.82, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇬🇷", callingCode: "+30", timezone: "UTC+2" },
  { name: "Hungary", iso3: "HUN", iso2: "HU", capital: "Budapest", region: "Central Europe", continent: "Europe", population: "9.7M", currency: "Forint", currencyCode: "HUF", languages: ["Hungarian"], lat: 47.16, lng: 19.50, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇭🇺", callingCode: "+36", timezone: "UTC+1" },
  { name: "Iceland", iso3: "ISL", iso2: "IS", capital: "Reykjavik", region: "Northern Europe", continent: "Europe", population: "0.4M", currency: "Króna", currencyCode: "ISK", languages: ["Icelandic"], lat: 64.96, lng: -19.02, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇮🇸", callingCode: "+354", timezone: "UTC+0" },
  { name: "Ireland", iso3: "IRL", iso2: "IE", capital: "Dublin", region: "Northern Europe", continent: "Europe", population: "5M", currency: "Euro", currencyCode: "EUR", languages: ["English", "Irish"], lat: 53.14, lng: -7.69, visaStatus: "visa-required", visaNote: "Irish visa required (separate from Schengen).", safetyLevel: "safe", flagEmoji: "🇮🇪", callingCode: "+353", timezone: "UTC+0" },
  { name: "Italy", iso3: "ITA", iso2: "IT", capital: "Rome", region: "Southern Europe", continent: "Europe", population: "60M", currency: "Euro", currencyCode: "EUR", languages: ["Italian"], lat: 41.87, lng: 12.57, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇮🇹", callingCode: "+39", timezone: "UTC+1" },
  { name: "Latvia", iso3: "LVA", iso2: "LV", capital: "Riga", region: "Northern Europe", continent: "Europe", population: "1.8M", currency: "Euro", currencyCode: "EUR", languages: ["Latvian"], lat: 56.88, lng: 24.60, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇱🇻", callingCode: "+371", timezone: "UTC+2" },
  { name: "Lithuania", iso3: "LTU", iso2: "LT", capital: "Vilnius", region: "Northern Europe", continent: "Europe", population: "2.8M", currency: "Euro", currencyCode: "EUR", languages: ["Lithuanian"], lat: 55.17, lng: 23.88, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇱🇹", callingCode: "+370", timezone: "UTC+2" },
  { name: "Luxembourg", iso3: "LUX", iso2: "LU", capital: "Luxembourg City", region: "Western Europe", continent: "Europe", population: "0.6M", currency: "Euro", currencyCode: "EUR", languages: ["Luxembourgish", "French", "German"], lat: 49.82, lng: 6.13, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇱🇺", callingCode: "+352", timezone: "UTC+1" },
  { name: "Malta", iso3: "MLT", iso2: "MT", capital: "Valletta", region: "Southern Europe", continent: "Europe", population: "0.5M", currency: "Euro", currencyCode: "EUR", languages: ["Maltese", "English"], lat: 35.94, lng: 14.37, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇲🇹", callingCode: "+356", timezone: "UTC+1" },
  { name: "Moldova", iso3: "MDA", iso2: "MD", capital: "Chișinău", region: "Eastern Europe", continent: "Europe", population: "2.6M", currency: "Leu", currencyCode: "MDL", languages: ["Romanian"], lat: 47.41, lng: 28.37, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇲🇩", callingCode: "+373", timezone: "UTC+2" },
  { name: "Monaco", iso3: "MCO", iso2: "MC", capital: "Monaco", region: "Western Europe", continent: "Europe", population: "0.04M", currency: "Euro", currencyCode: "EUR", languages: ["French"], lat: 43.73, lng: 7.42, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇲🇨", callingCode: "+377", timezone: "UTC+1" },
  { name: "Montenegro", iso3: "MNE", iso2: "ME", capital: "Podgorica", region: "Southern Europe", continent: "Europe", population: "0.6M", currency: "Euro", currencyCode: "EUR", languages: ["Montenegrin"], lat: 42.71, lng: 19.37, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇲🇪", callingCode: "+382", timezone: "UTC+1" },
  { name: "Netherlands", iso3: "NLD", iso2: "NL", capital: "Amsterdam", region: "Western Europe", continent: "Europe", population: "17.5M", currency: "Euro", currencyCode: "EUR", languages: ["Dutch"], lat: 52.13, lng: 5.29, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇳🇱", callingCode: "+31", timezone: "UTC+1" },
  { name: "North Macedonia", iso3: "MKD", iso2: "MK", capital: "Skopje", region: "Southern Europe", continent: "Europe", population: "1.8M", currency: "Denar", currencyCode: "MKD", languages: ["Macedonian"], lat: 41.51, lng: 21.75, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇲🇰", callingCode: "+389", timezone: "UTC+1" },
  { name: "Norway", iso3: "NOR", iso2: "NO", capital: "Oslo", region: "Northern Europe", continent: "Europe", population: "5.4M", currency: "Krone", currencyCode: "NOK", languages: ["Norwegian"], lat: 60.47, lng: 8.47, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇳🇴", callingCode: "+47", timezone: "UTC+1" },
  { name: "Poland", iso3: "POL", iso2: "PL", capital: "Warsaw", region: "Central Europe", continent: "Europe", population: "38M", currency: "Złoty", currencyCode: "PLN", languages: ["Polish"], lat: 51.92, lng: 19.15, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇵🇱", callingCode: "+48", timezone: "UTC+1" },
  { name: "Portugal", iso3: "PRT", iso2: "PT", capital: "Lisbon", region: "Southern Europe", continent: "Europe", population: "10.3M", currency: "Euro", currencyCode: "EUR", languages: ["Portuguese"], lat: 39.40, lng: -8.22, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇵🇹", callingCode: "+351", timezone: "UTC+0" },
  { name: "Romania", iso3: "ROU", iso2: "RO", capital: "Bucharest", region: "Eastern Europe", continent: "Europe", population: "19M", currency: "Leu", currencyCode: "RON", languages: ["Romanian"], lat: 45.94, lng: 24.97, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇷🇴", callingCode: "+40", timezone: "UTC+2" },
  { name: "Russia", iso3: "RUS", iso2: "RU", capital: "Moscow", region: "Eastern Europe", continent: "Europe", population: "146M", currency: "Ruble", currencyCode: "RUB", languages: ["Russian"], lat: 61.52, lng: 105.32, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇷🇺", callingCode: "+7", timezone: "UTC+3" },
  { name: "Serbia", iso3: "SRB", iso2: "RS", capital: "Belgrade", region: "Southern Europe", continent: "Europe", population: "6.8M", currency: "Dinar", currencyCode: "RSD", languages: ["Serbian"], lat: 44.02, lng: 21.01, visaStatus: "visa-free", visaNote: "Visa-free for 30 days.", safetyLevel: "safe", flagEmoji: "🇷🇸", callingCode: "+381", timezone: "UTC+1" },
  { name: "Slovakia", iso3: "SVK", iso2: "SK", capital: "Bratislava", region: "Central Europe", continent: "Europe", population: "5.4M", currency: "Euro", currencyCode: "EUR", languages: ["Slovak"], lat: 48.67, lng: 19.70, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇸🇰", callingCode: "+421", timezone: "UTC+1" },
  { name: "Slovenia", iso3: "SVN", iso2: "SI", capital: "Ljubljana", region: "Central Europe", continent: "Europe", population: "2.1M", currency: "Euro", currencyCode: "EUR", languages: ["Slovene"], lat: 46.15, lng: 14.99, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇸🇮", callingCode: "+386", timezone: "UTC+1" },
  { name: "Spain", iso3: "ESP", iso2: "ES", capital: "Madrid", region: "Southern Europe", continent: "Europe", population: "47M", currency: "Euro", currencyCode: "EUR", languages: ["Spanish"], lat: 40.46, lng: -3.75, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇪🇸", callingCode: "+34", timezone: "UTC+1" },
  { name: "Sweden", iso3: "SWE", iso2: "SE", capital: "Stockholm", region: "Northern Europe", continent: "Europe", population: "10.4M", currency: "Krona", currencyCode: "SEK", languages: ["Swedish"], lat: 60.13, lng: 18.64, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇸🇪", callingCode: "+46", timezone: "UTC+1" },
  { name: "Switzerland", iso3: "CHE", iso2: "CH", capital: "Bern", region: "Western Europe", continent: "Europe", population: "8.8M", currency: "Franc", currencyCode: "CHF", languages: ["German", "French", "Italian"], lat: 46.82, lng: 8.23, visaStatus: "visa-required", visaNote: "Schengen visa required.", safetyLevel: "safe", flagEmoji: "🇨🇭", callingCode: "+41", timezone: "UTC+1" },
  { name: "Ukraine", iso3: "UKR", iso2: "UA", capital: "Kyiv", region: "Eastern Europe", continent: "Europe", population: "37M", currency: "Hryvnia", currencyCode: "UAH", languages: ["Ukrainian"], lat: 48.38, lng: 31.17, visaStatus: "visa-required", visaNote: "Visa required. Travel advisory.", safetyLevel: "avoid", flagEmoji: "🇺🇦", callingCode: "+380", timezone: "UTC+2" },
  { name: "United Kingdom", iso3: "GBR", iso2: "GB", capital: "London", region: "Northern Europe", continent: "Europe", population: "67M", currency: "Pound", currencyCode: "GBP", languages: ["English"], lat: 55.38, lng: -3.44, visaStatus: "visa-required", visaNote: "UK visa required (separate from Schengen).", safetyLevel: "safe", flagEmoji: "🇬🇧", callingCode: "+44", timezone: "UTC+0" },

  // ═══════ AFRICA ═══════
  { name: "Algeria", iso3: "DZA", iso2: "DZ", capital: "Algiers", region: "North Africa", continent: "Africa", population: "45M", currency: "Dinar", currencyCode: "DZD", languages: ["Arabic"], lat: 28.03, lng: 1.66, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇩🇿", callingCode: "+213", timezone: "UTC+1" },
  { name: "Egypt", iso3: "EGY", iso2: "EG", capital: "Cairo", region: "North Africa", continent: "Africa", population: "104M", currency: "Pound", currencyCode: "EGP", languages: ["Arabic"], lat: 26.82, lng: 30.80, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "moderate", flagEmoji: "🇪🇬", callingCode: "+20", timezone: "UTC+2" },
  { name: "Ethiopia", iso3: "ETH", iso2: "ET", capital: "Addis Ababa", region: "East Africa", continent: "Africa", population: "120M", currency: "Birr", currencyCode: "ETB", languages: ["Amharic"], lat: 9.15, lng: 40.49, visaStatus: "e-visa", visaNote: "E-visa available for 30/90 days.", safetyLevel: "caution", flagEmoji: "🇪🇹", callingCode: "+251", timezone: "UTC+3" },
  { name: "Ghana", iso3: "GHA", iso2: "GH", capital: "Accra", region: "West Africa", continent: "Africa", population: "33M", currency: "Cedi", currencyCode: "GHS", languages: ["English"], lat: 7.95, lng: -1.02, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇬🇭", callingCode: "+233", timezone: "UTC+0" },
  { name: "Kenya", iso3: "KEN", iso2: "KE", capital: "Nairobi", region: "East Africa", continent: "Africa", population: "55M", currency: "Shilling", currencyCode: "KES", languages: ["English", "Swahili"], lat: -0.02, lng: 37.91, visaStatus: "e-visa", visaNote: "E-visa available for 90 days.", safetyLevel: "moderate", flagEmoji: "🇰🇪", callingCode: "+254", timezone: "UTC+3" },
  { name: "Libya", iso3: "LBY", iso2: "LY", capital: "Tripoli", region: "North Africa", continent: "Africa", population: "7M", currency: "Dinar", currencyCode: "LYD", languages: ["Arabic"], lat: 26.34, lng: 17.23, visaStatus: "visa-required", visaNote: "Travel not advised.", safetyLevel: "avoid", flagEmoji: "🇱🇾", callingCode: "+218", timezone: "UTC+2" },
  { name: "Madagascar", iso3: "MDG", iso2: "MG", capital: "Antananarivo", region: "East Africa", continent: "Africa", population: "29M", currency: "Ariary", currencyCode: "MGA", languages: ["Malagasy", "French"], lat: -18.77, lng: 46.87, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30/60/90 days.", safetyLevel: "moderate", flagEmoji: "🇲🇬", callingCode: "+261", timezone: "UTC+3" },
  { name: "Mauritius", iso3: "MUS", iso2: "MU", capital: "Port Louis", region: "East Africa", continent: "Africa", population: "1.3M", currency: "Rupee", currencyCode: "MUR", languages: ["English", "French"], lat: -20.35, lng: 57.55, visaStatus: "visa-free", visaNote: "Visa-free for 90 days.", safetyLevel: "safe", flagEmoji: "🇲🇺", callingCode: "+230", timezone: "UTC+4" },
  { name: "Morocco", iso3: "MAR", iso2: "MA", capital: "Rabat", region: "North Africa", continent: "Africa", population: "37M", currency: "Dirham", currencyCode: "MAD", languages: ["Arabic", "Berber"], lat: 31.79, lng: -7.09, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇲🇦", callingCode: "+212", timezone: "UTC+1" },
  { name: "Mozambique", iso3: "MOZ", iso2: "MZ", capital: "Maputo", region: "Southeast Africa", continent: "Africa", population: "32M", currency: "Metical", currencyCode: "MZN", languages: ["Portuguese"], lat: -18.67, lng: 35.53, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "caution", flagEmoji: "🇲🇿", callingCode: "+258", timezone: "UTC+2" },
  { name: "Nigeria", iso3: "NGA", iso2: "NG", capital: "Abuja", region: "West Africa", continent: "Africa", population: "223M", currency: "Naira", currencyCode: "NGN", languages: ["English"], lat: 9.08, lng: 7.49, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇳🇬", callingCode: "+234", timezone: "UTC+1" },
  { name: "Rwanda", iso3: "RWA", iso2: "RW", capital: "Kigali", region: "East Africa", continent: "Africa", population: "13M", currency: "Franc", currencyCode: "RWF", languages: ["Kinyarwanda", "English", "French"], lat: -1.94, lng: 29.87, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "safe", flagEmoji: "🇷🇼", callingCode: "+250", timezone: "UTC+2" },
  { name: "Seychelles", iso3: "SYC", iso2: "SC", capital: "Victoria", region: "East Africa", continent: "Africa", population: "0.1M", currency: "Rupee", currencyCode: "SCR", languages: ["English", "French", "Seychellois Creole"], lat: -4.68, lng: 55.49, visaStatus: "visa-free", visaNote: "Visa-free for 3 months.", safetyLevel: "safe", flagEmoji: "🇸🇨", callingCode: "+248", timezone: "UTC+4" },
  { name: "Somalia", iso3: "SOM", iso2: "SO", capital: "Mogadishu", region: "East Africa", continent: "Africa", population: "18M", currency: "Shilling", currencyCode: "SOS", languages: ["Somali", "Arabic"], lat: 5.15, lng: 46.20, visaStatus: "visa-required", visaNote: "Travel not advised.", safetyLevel: "avoid", flagEmoji: "🇸🇴", callingCode: "+252", timezone: "UTC+3" },
  { name: "South Africa", iso3: "ZAF", iso2: "ZA", capital: "Pretoria", region: "Southern Africa", continent: "Africa", population: "60M", currency: "Rand", currencyCode: "ZAR", languages: ["English", "Afrikaans", "Zulu"], lat: -30.56, lng: 22.94, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇿🇦", callingCode: "+27", timezone: "UTC+2" },
  { name: "Sudan", iso3: "SDN", iso2: "SD", capital: "Khartoum", region: "North Africa", continent: "Africa", population: "46M", currency: "Pound", currencyCode: "SDG", languages: ["Arabic", "English"], lat: 12.86, lng: 30.22, visaStatus: "visa-required", visaNote: "Travel advisory.", safetyLevel: "avoid", flagEmoji: "🇸🇩", callingCode: "+249", timezone: "UTC+2" },
  { name: "Tanzania", iso3: "TZA", iso2: "TZ", capital: "Dodoma", region: "East Africa", continent: "Africa", population: "65M", currency: "Shilling", currencyCode: "TZS", languages: ["Swahili", "English"], lat: -6.37, lng: 34.89, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival or e-visa for 90 days.", safetyLevel: "moderate", flagEmoji: "🇹🇿", callingCode: "+255", timezone: "UTC+3" },
  { name: "Tunisia", iso3: "TUN", iso2: "TN", capital: "Tunis", region: "North Africa", continent: "Africa", population: "12M", currency: "Dinar", currencyCode: "TND", languages: ["Arabic"], lat: 33.89, lng: 9.54, visaStatus: "visa-free", visaNote: "Visa-free for 90 days.", safetyLevel: "moderate", flagEmoji: "🇹🇳", callingCode: "+216", timezone: "UTC+1" },
  { name: "Uganda", iso3: "UGA", iso2: "UG", capital: "Kampala", region: "East Africa", continent: "Africa", population: "47M", currency: "Shilling", currencyCode: "UGX", languages: ["English", "Swahili"], lat: 1.37, lng: 32.29, visaStatus: "e-visa", visaNote: "E-visa required before arrival.", safetyLevel: "moderate", flagEmoji: "🇺🇬", callingCode: "+256", timezone: "UTC+3" },
  { name: "Zimbabwe", iso3: "ZWE", iso2: "ZW", capital: "Harare", region: "Southern Africa", continent: "Africa", population: "16M", currency: "Dollar", currencyCode: "ZWL", languages: ["English", "Shona", "Ndebele"], lat: -19.02, lng: 29.15, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 30 days.", safetyLevel: "moderate", flagEmoji: "🇿🇼", callingCode: "+263", timezone: "UTC+2" },

  // ═══════ NORTH AMERICA ═══════
  { name: "Canada", iso3: "CAN", iso2: "CA", capital: "Ottawa", region: "North America", continent: "North America", population: "39M", currency: "Dollar", currencyCode: "CAD", languages: ["English", "French"], lat: 56.13, lng: -106.35, visaStatus: "visa-required", visaNote: "Visa required. Apply online or at embassy.", safetyLevel: "safe", flagEmoji: "🇨🇦", callingCode: "+1", timezone: "UTC-5" },
  { name: "Costa Rica", iso3: "CRI", iso2: "CR", capital: "San José", region: "Central America", continent: "North America", population: "5.2M", currency: "Colón", currencyCode: "CRC", languages: ["Spanish"], lat: 9.75, lng: -83.75, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇨🇷", callingCode: "+506", timezone: "UTC-6" },
  { name: "Cuba", iso3: "CUB", iso2: "CU", capital: "Havana", region: "Caribbean", continent: "North America", population: "11M", currency: "Peso", currencyCode: "CUP", languages: ["Spanish"], lat: 21.52, lng: -77.78, visaStatus: "visa-required", visaNote: "Tourist card required.", safetyLevel: "moderate", flagEmoji: "🇨🇺", callingCode: "+53", timezone: "UTC-5" },
  { name: "Dominican Republic", iso3: "DOM", iso2: "DO", capital: "Santo Domingo", region: "Caribbean", continent: "North America", population: "11M", currency: "Peso", currencyCode: "DOP", languages: ["Spanish"], lat: 18.74, lng: -70.16, visaStatus: "visa-free", visaNote: "Visa-free for 30 days.", safetyLevel: "moderate", flagEmoji: "🇩🇴", callingCode: "+1-809", timezone: "UTC-4" },
  { name: "El Salvador", iso3: "SLV", iso2: "SV", capital: "San Salvador", region: "Central America", continent: "North America", population: "6.3M", currency: "US Dollar", currencyCode: "USD", languages: ["Spanish"], lat: 13.79, lng: -88.90, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇸🇻", callingCode: "+503", timezone: "UTC-6" },
  { name: "Guatemala", iso3: "GTM", iso2: "GT", capital: "Guatemala City", region: "Central America", continent: "North America", population: "18M", currency: "Quetzal", currencyCode: "GTQ", languages: ["Spanish"], lat: 15.78, lng: -90.23, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇬🇹", callingCode: "+502", timezone: "UTC-6" },
  { name: "Haiti", iso3: "HTI", iso2: "HT", capital: "Port-au-Prince", region: "Caribbean", continent: "North America", population: "11.4M", currency: "Gourde", currencyCode: "HTG", languages: ["French", "Creole"], lat: 18.97, lng: -72.29, visaStatus: "visa-free", visaNote: "Visa-free for 90 days.", safetyLevel: "avoid", flagEmoji: "🇭🇹", callingCode: "+509", timezone: "UTC-5" },
  { name: "Honduras", iso3: "HND", iso2: "HN", capital: "Tegucigalpa", region: "Central America", continent: "North America", population: "10M", currency: "Lempira", currencyCode: "HNL", languages: ["Spanish"], lat: 15.20, lng: -86.24, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇭🇳", callingCode: "+504", timezone: "UTC-6" },
  { name: "Jamaica", iso3: "JAM", iso2: "JM", capital: "Kingston", region: "Caribbean", continent: "North America", population: "3M", currency: "Dollar", currencyCode: "JMD", languages: ["English"], lat: 18.11, lng: -77.30, visaStatus: "visa-free", visaNote: "Visa-free for 14 days.", safetyLevel: "moderate", flagEmoji: "🇯🇲", callingCode: "+1-876", timezone: "UTC-5" },
  { name: "Mexico", iso3: "MEX", iso2: "MX", capital: "Mexico City", region: "North America", continent: "North America", population: "129M", currency: "Peso", currencyCode: "MXN", languages: ["Spanish"], lat: 23.63, lng: -102.55, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇲🇽", callingCode: "+52", timezone: "UTC-6" },
  { name: "Nicaragua", iso3: "NIC", iso2: "NI", capital: "Managua", region: "Central America", continent: "North America", population: "6.9M", currency: "Córdoba", currencyCode: "NIO", languages: ["Spanish"], lat: 12.87, lng: -85.21, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "caution", flagEmoji: "🇳🇮", callingCode: "+505", timezone: "UTC-6" },
  { name: "Panama", iso3: "PAN", iso2: "PA", capital: "Panama City", region: "Central America", continent: "North America", population: "4.4M", currency: "Balboa/USD", currencyCode: "PAB", languages: ["Spanish"], lat: 8.54, lng: -80.78, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇵🇦", callingCode: "+507", timezone: "UTC-5" },
  { name: "Trinidad and Tobago", iso3: "TTO", iso2: "TT", capital: "Port of Spain", region: "Caribbean", continent: "North America", population: "1.4M", currency: "Dollar", currencyCode: "TTD", languages: ["English"], lat: 10.69, lng: -61.22, visaStatus: "visa-free", visaNote: "Visa-free for 90 days.", safetyLevel: "moderate", flagEmoji: "🇹🇹", callingCode: "+1-868", timezone: "UTC-4" },
  { name: "United States", iso3: "USA", iso2: "US", capital: "Washington, D.C.", region: "North America", continent: "North America", population: "332M", currency: "Dollar", currencyCode: "USD", languages: ["English"], lat: 37.09, lng: -95.71, visaStatus: "visa-required", visaNote: "B1/B2 visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇺🇸", callingCode: "+1", timezone: "UTC-5" },

  // ═══════ SOUTH AMERICA ═══════
  { name: "Argentina", iso3: "ARG", iso2: "AR", capital: "Buenos Aires", region: "South America", continent: "South America", population: "46M", currency: "Peso", currencyCode: "ARS", languages: ["Spanish"], lat: -38.42, lng: -63.62, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇦🇷", callingCode: "+54", timezone: "UTC-3" },
  { name: "Bolivia", iso3: "BOL", iso2: "BO", capital: "Sucre", region: "South America", continent: "South America", population: "12M", currency: "Boliviano", currencyCode: "BOB", languages: ["Spanish"], lat: -16.29, lng: -63.59, visaStatus: "visa-free", visaNote: "Visa-free for 90 days.", safetyLevel: "moderate", flagEmoji: "🇧🇴", callingCode: "+591", timezone: "UTC-4" },
  { name: "Brazil", iso3: "BRA", iso2: "BR", capital: "Brasília", region: "South America", continent: "South America", population: "215M", currency: "Real", currencyCode: "BRL", languages: ["Portuguese"], lat: -14.24, lng: -51.93, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇧🇷", callingCode: "+55", timezone: "UTC-3" },
  { name: "Chile", iso3: "CHL", iso2: "CL", capital: "Santiago", region: "South America", continent: "South America", population: "19M", currency: "Peso", currencyCode: "CLP", languages: ["Spanish"], lat: -35.68, lng: -71.54, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇨🇱", callingCode: "+56", timezone: "UTC-4" },
  { name: "Colombia", iso3: "COL", iso2: "CO", capital: "Bogotá", region: "South America", continent: "South America", population: "52M", currency: "Peso", currencyCode: "COP", languages: ["Spanish"], lat: 4.57, lng: -74.30, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇨🇴", callingCode: "+57", timezone: "UTC-5" },
  { name: "Ecuador", iso3: "ECU", iso2: "EC", capital: "Quito", region: "South America", continent: "South America", population: "18M", currency: "US Dollar", currencyCode: "USD", languages: ["Spanish"], lat: -1.83, lng: -78.18, visaStatus: "visa-free", visaNote: "Visa-free for 90 days.", safetyLevel: "moderate", flagEmoji: "🇪🇨", callingCode: "+593", timezone: "UTC-5" },
  { name: "Guyana", iso3: "GUY", iso2: "GY", capital: "Georgetown", region: "South America", continent: "South America", population: "0.8M", currency: "Dollar", currencyCode: "GYD", languages: ["English"], lat: 4.86, lng: -58.93, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇬🇾", callingCode: "+592", timezone: "UTC-4" },
  { name: "Paraguay", iso3: "PRY", iso2: "PY", capital: "Asunción", region: "South America", continent: "South America", population: "7.1M", currency: "Guaraní", currencyCode: "PYG", languages: ["Spanish", "Guarani"], lat: -23.44, lng: -58.44, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇵🇾", callingCode: "+595", timezone: "UTC-4" },
  { name: "Peru", iso3: "PER", iso2: "PE", capital: "Lima", region: "South America", continent: "South America", population: "34M", currency: "Sol", currencyCode: "PEN", languages: ["Spanish"], lat: -9.19, lng: -75.02, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇵🇪", callingCode: "+51", timezone: "UTC-5" },
  { name: "Suriname", iso3: "SUR", iso2: "SR", capital: "Paramaribo", region: "South America", continent: "South America", population: "0.6M", currency: "Dollar", currencyCode: "SRD", languages: ["Dutch"], lat: 3.92, lng: -56.03, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "moderate", flagEmoji: "🇸🇷", callingCode: "+597", timezone: "UTC-3" },
  { name: "Uruguay", iso3: "URY", iso2: "UY", capital: "Montevideo", region: "South America", continent: "South America", population: "3.5M", currency: "Peso", currencyCode: "UYU", languages: ["Spanish"], lat: -32.52, lng: -55.77, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇺🇾", callingCode: "+598", timezone: "UTC-3" },
  { name: "Venezuela", iso3: "VEN", iso2: "VE", capital: "Caracas", region: "South America", continent: "South America", population: "28M", currency: "Bolívar", currencyCode: "VES", languages: ["Spanish"], lat: 6.42, lng: -66.59, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "avoid", flagEmoji: "🇻🇪", callingCode: "+58", timezone: "UTC-4" },

  // ═══════ OCEANIA ═══════
  { name: "Australia", iso3: "AUS", iso2: "AU", capital: "Canberra", region: "Oceania", continent: "Oceania", population: "26M", currency: "Dollar", currencyCode: "AUD", languages: ["English"], lat: -25.27, lng: 133.78, visaStatus: "visa-required", visaNote: "ETA or visa required. Apply online.", safetyLevel: "safe", flagEmoji: "🇦🇺", callingCode: "+61", timezone: "UTC+10" },
  { name: "Fiji", iso3: "FJI", iso2: "FJ", capital: "Suva", region: "Oceania", continent: "Oceania", population: "0.9M", currency: "Dollar", currencyCode: "FJD", languages: ["English", "Fijian"], lat: -17.71, lng: 178.07, visaStatus: "visa-free", visaNote: "Visa-free for 4 months.", safetyLevel: "safe", flagEmoji: "🇫🇯", callingCode: "+679", timezone: "UTC+12" },
  { name: "New Zealand", iso3: "NZL", iso2: "NZ", capital: "Wellington", region: "Oceania", continent: "Oceania", population: "5.1M", currency: "Dollar", currencyCode: "NZD", languages: ["English", "Maori"], lat: -40.90, lng: 174.89, visaStatus: "visa-required", visaNote: "Visa required. Apply at embassy.", safetyLevel: "safe", flagEmoji: "🇳🇿", callingCode: "+64", timezone: "UTC+12" },
  { name: "Papua New Guinea", iso3: "PNG", iso2: "PG", capital: "Port Moresby", region: "Oceania", continent: "Oceania", population: "10M", currency: "Kina", currencyCode: "PGK", languages: ["English", "Tok Pisin"], lat: -6.31, lng: 143.96, visaStatus: "visa-on-arrival", visaNote: "Visa on arrival for 60 days.", safetyLevel: "caution", flagEmoji: "🇵🇬", callingCode: "+675", timezone: "UTC+10" },
  { name: "Samoa", iso3: "WSM", iso2: "WS", capital: "Apia", region: "Oceania", continent: "Oceania", population: "0.2M", currency: "Tala", currencyCode: "WST", languages: ["Samoan", "English"], lat: -13.76, lng: -172.10, visaStatus: "visa-free", visaNote: "Entry permit on arrival for 60 days.", safetyLevel: "safe", flagEmoji: "🇼🇸", callingCode: "+685", timezone: "UTC+13" },
  { name: "Tonga", iso3: "TON", iso2: "TO", capital: "Nukuʻalofa", region: "Oceania", continent: "Oceania", population: "0.1M", currency: "Paʻanga", currencyCode: "TOP", languages: ["Tongan", "English"], lat: -21.18, lng: -175.20, visaStatus: "visa-free", visaNote: "Visa-free for 31 days.", safetyLevel: "safe", flagEmoji: "🇹🇴", callingCode: "+676", timezone: "UTC+13" },
  { name: "Vanuatu", iso3: "VUT", iso2: "VU", capital: "Port Vila", region: "Oceania", continent: "Oceania", population: "0.3M", currency: "Vatu", currencyCode: "VUV", languages: ["Bislama", "English", "French"], lat: -15.38, lng: 166.96, visaStatus: "visa-free", visaNote: "Visa-free for 30 days.", safetyLevel: "safe", flagEmoji: "🇻🇺", callingCode: "+678", timezone: "UTC+11" },
];

// Continent color mapping for the globe
export const CONTINENT_COLORS: Record<string, string> = {
  "Asia": "#f59e0b",
  "Europe": "#3b82f6",
  "Africa": "#10b981",
  "North America": "#ef4444",
  "South America": "#8b5cf6",
  "Oceania": "#06b6d4",
};

// Visa status color mapping
export const VISA_STATUS_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  "visa-free": { bg: "bg-emerald-500/20", text: "text-emerald-400", border: "border-emerald-500/30" },
  "visa-on-arrival": { bg: "bg-blue-500/20", text: "text-blue-400", border: "border-blue-500/30" },
  "e-visa": { bg: "bg-amber-500/20", text: "text-amber-400", border: "border-amber-500/30" },
  "visa-required": { bg: "bg-red-500/20", text: "text-red-400", border: "border-red-500/30" },
};

// Safety level color mapping
export const SAFETY_COLORS: Record<string, { bg: string; text: string; label: string }> = {
  "safe": { bg: "bg-emerald-500/20", text: "text-emerald-400", label: "Safe" },
  "moderate": { bg: "bg-yellow-500/20", text: "text-yellow-400", label: "Exercise Caution" },
  "caution": { bg: "bg-orange-500/20", text: "text-orange-400", label: "High Caution" },
  "avoid": { bg: "bg-red-500/20", text: "text-red-400", label: "Do Not Travel" },
};
